---

services:
  xui:
    build: .  # означает, что Dockerfile для сборки нужно искать в этой же директории
    container_name: x-kmui
    hostname: learny.mooo.com
    networks:
      - x-kmui-net
    ports:
      - "127.0.0.1:54321:54321"  # FIXME: дефолтный нужно будет перенастроить в конфиге
      - "127.0.0.1:54233:54233"
      - "4333:443"  # Reality for all ips on custom port 4333
      # - "80:80"    # Для ACME/редиректов
    volumes:
      # если панель, вдруг, станет недоступной после её некорректной настройки,
      # можно будет исправить ошибочные ключи правкой БД
      # sudo apt install sqlite3 -y && sudo sqlite3 _volume_uidb/x-ui.db
      # .help
      # .tables
      # .schema settings
      # select * from settings;
      # update settings set value=null where key='webDomain';
      - ./_volume_uidb:/home/app/etc/x-ui:rw
      - ./_volume_cert:/home/app/cert:rw
    environment:
      # Должно совпадать с volume, чтобы хранилище сертификатов могло писаться
      # непривилегированным пользователем и сохраняться между пересозданиями контейнера
      XUI_DB_FOLDER: /home/app/etc/x-ui
    user: "5055:5055"  # Явно указываем пользователя (точнее, достаточно uid:gid, тогда можно даже не создавать реального)
    # restart: on-failure:3
    restart: always  # в проде нам нужна максимальная выживаемость
    command: ./x-ui  # внутри Dockerfile устанавливается WORKDIR, поэтому можно локальный путь

networks:
  x-kmui-net:
    driver: bridge  # позволяет не светить порты контейнера наружу хоста, обойтись маппингом необходимых
    ipam:
      config:
        # кастомная сеть подальше от коллизий с дефолтными попытками docker'а
        - subnet: 172.200.0.0/24
